"""empty message

Revision ID: 13c58f234b3a
Revises: f1f0c4c9a807
Create Date: 2021-04-08 10:18:27.697772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c58f234b3a'
down_revision = 'f1f0c4c9a807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'genres', postgresql_using="genres::character varying[]", existing_type=sa.String, type_=sa.ARRAY(sa.String))
    op.alter_column('venues', 'genres', postgresql_using="genres::character varying[]", existing_type=sa.String, type_=sa.ARRAY(sa.String))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'genres', existing_type=sa.ARRAY(sa.String), type_=sa.String)
    op.alter_column('venues', 'genres', existing_type=sa.ARRAY(sa.String), type_=sa.String)
    # ### end Alembic commands ###
