"""empty message

Revision ID: 1623a28c7fe5
Revises: 13c58f234b3a
Create Date: 2021-04-09 07:28:34.763093

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '1623a28c7fe5'
down_revision = '13c58f234b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('availability_restriction', sa.Boolean(), nullable=True))
    op.execute('UPDATE artists SET availability_restriction = False')
    op.alter_column('artists', 'availability_restriction', nullable=False)
    op.add_column('artists', sa.Column('from_time', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('to_time', sa.String(), nullable=True))
    op.execute(f'UPDATE artists SET from_time = \'{datetime.now()}\' WHERE from_time IS NULL')
    op.execute(f'UPDATE artists SET to_time = \'{datetime.now()}\' WHERE to_time IS NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'to_time')
    op.drop_column('artists', 'from_time')
    op.drop_column('artists', 'availability_restriction')
    # ### end Alembic commands ###
